<a href="https://colab.research.google.com/github/DLuisMontufar3/1/blob/main/Si7_iipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*07 SEGMENTACION DE DATOS MODELO RFM*

Paso 1: Generacion carga y Exploracion de Datos

In [ ]:
import pandas as pd
import numpy as np
import datetime

Transformar el registro histórico de transacciones (datos crudos) en una Matriz de Segmentación RFM estratégica para responder:

¿Quiénes son nuestros clientes "Campeones"? (Compran mucho y seguido).
¿Quiénes son nuestros clientes "En Riesgo"? (Compraban mucho antes, pero se han ido).
¿Quiénes son "Leales"? (Compran seguido).

In [ ]:
np.random.seed(42)
n_transacciones = 1000
n_clientes = 50

In [ ]:
fechas = pd.date_range(start='2023-01-01', end='2023-12-31', periods=n_transacciones)
fechas = np.random.choice(fechas, n_transacciones) # Desordenar fechas
cliente_ids = np.random.randint(1000, 1000 + n_clientes, n_transacciones)
cantidades = np.random.randint(1, 10, n_transacciones)
precios = np.round(np.random.uniform(10, 100, n_transacciones), 2)

In [ ]:
# Crear DataFrame
df = pd.DataFrame({
    'ID_Transaccion': [f'TRX-{i}' for i in range(n_transacciones)],
    'ID_Cliente': cliente_ids,
    'Fecha': fechas,
    'Cantidad': cantidades,
    'Precio_Unitario': precios
})

# Calcular Total y Guardar
df['Total'] = df['Cantidad'] * df['Precio_Unitario']

In [ ]:
df

,ID_Transaccion,ID_Cliente,Fecha,Cantidad,Precio_Unitario,Total
0,TRX-0,1044,2023-02-07 03:57:50.270270270,5,30.28,151.40
1,TRX-1,1004,2023-06-08 11:57:50.270270270,9,32.59,293.31
2,TRX-2,1032,2023-11-10 08:28:49.729729732,3,86.56,259.68
3,TRX-3,1000,2023-04-09 09:04:51.891891892,7,60.51,423.57
4,TRX-4,1017,2023-02-08 14:56:34.594594594,5,57.11,285.55
...,...,...,...,...,...,...
995,TRX-995,1041,2023-01-04 06:42:09.729729729,9,19.12,172.08
996,TRX-996,1035,2023-10-27 20:55:29.729729732,9,35.01,315.09
997,TRX-997,1026,2023-10-18 09:33:41.621621624,1,34.87,34.87
998,TRX-998,1037,2023-03-29 19:29:00.540540541,2,48.88,97.76
999,TRX-999,1006,2023-04-02 02:11:10.270270271,5,98.23,491.15

2.1 Recencia

In [ ]:
df['Fecha'].max()

Timestamp('2023-12-30 15:15:18.918918920')

In [ ]:
df.groupby('ID_Cliente')['Fecha'].max()

ID_Cliente
1000   2023-12-20 01:39:27.567567568
1001   2023-12-29 21:45:56.756756756
1002   2023-12-29 21:45:56.756756756
1003   2023-12-22 06:07:34.054054056
1004   2023-12-24 10:35:40.540540540
1005   2023-12-29 13:01:15.675675676
1006   2023-11-30 00:41:48.108108108
1007   2023-12-30 15:15:18.918918920
1008   2023-12-21 12:38:11.891891892
1009   2023-12-01 20:25:13.513513516
1010   2023-12-28 10:47:12.432432432
1011   2023-11-18 08:51:53.513513516
1012   2023-11-11 01:58:11.891891892
1013   2023-12-16 18:57:17.837837840
1014   2023-12-07 07:35:29.729729732
1015   2023-11-25 15:45:35.135135136
1016   2023-12-30 15:15:18.918918920
1017   2023-12-24 01:50:59.459459460
1018   2023-12-22 23:36:56.216216216
1019   2023-12-07 07:35:29.729729732
1020   2023-10-14 09:22:09.729729732
1021   2023-11-23 11:17:28.648648648
1022   2023-12-27 08:33:09.189189192
1023   2023-12-28 02:02:31.351351352
1024   2023-12-07 16:20:10.810810812
1025   2023-11-27 11:29:00.540540540
1026   2023-12-04 18:22:42.162162164
1027   2023-12-26 15:03:47.027027028
1028   2023-12-15 16:43:14.594594596
1029   2023-12-17 12:26:40.000000000
1030   2023-12-29 13:01:15.675675676
1031   2023-12-11 07:47:01.621621624
1032   2023-11-10 08:28:49.729729732
1033   2023-12-24 19:20:21.621621624
1034   2023-11-21 06:49:22.162162164
1035   2023-12-15 07:58:33.513513516
1036   2023-11-21 15:34:03.243243244
1037   2023-12-14 23:13:52.432432432
1038   2023-12-26 15:03:47.027027028
1039   2023-12-15 16:43:14.594594596
1040   2023-12-06 05:21:26.486486488
1041   2023-12-14 05:44:30.270270272
1042   2023-12-14 14:29:11.351351352
1043   2023-11-27 02:44:19.459459460
1044   2023-12-10 05:32:58.378378380
1045   2023-12-21 03:53:30.810810812
1046   2023-12-28 10:47:12.432432432
1047   2023-11-18 08:51:53.513513516
1048   2023-12-25 21:34:24.864864864
1049   2023-12-17 12:26:40.000000000
Name: Fecha, dtype: datetime64[ns]

In [ ]:
df['Fecha'] = pd.to_datetime(df['Fecha'])

In [ ]:
df_rfm = df.groupby('ID_Cliente')['Fecha'].max()

In [ ]:
#df_rfm = pd.DataFrame(groupby('ID_Cliente')['Fecha'].max())

In [ ]:
hoy = pd.to_datetime('today')

rfm = df.groupby('ID_Cliente')['Fecha'].max().rsub(hoy).dt.days.to_frame('Recencia')

rfm

            Recencia
ID_Cliente
1000             757
1001             748
1002             748
1003             755
1004             753
1005             748
1006             777
1007             747
1008             756
1009             776
1010             749
1011             789
1012             796
1013             761
1014             770
1015             782
1016             747
1017             753
1018             755
1019             770
1020             824
1021             784
1022             750
1023             749
1024             770
1025             780
1026             773
1027             751
1028             762
1029             760
1030             748
1031             766
1032             797
1033             753
1034             786
1035             762
1036             786
1037             763
1038             751
1039             762
1040             771
1041             763
1042             763
1043             780
1044             767
1045             756
1046             749
1047             789
1048             752
1049             760

In [ ]:

frecuencia = df.groupby('ID_Cliente')['ID_Transaccion'].nunique().to_frame('Frecuencia')

frecuencia.head()

            Frecuencia
ID_Cliente
1000                21
1001                18
1002                21
1003                20
1004                25

In [ ]:
monetario = df.groupby('ID_Cliente')['Total'].sum().to_frame('Monetario')

monetario.head()

            Monetario
ID_Cliente
1000          5304.32
1001          5528.83
1002          4389.77
1003          4860.34
1004          8050.55

In [ ]:
rfm = rfm.join(frecuencia).join(monetario)
rfm.head()

            Recencia  Frecuencia  Monetario
ID_Cliente
1000             757          21    5304.32
1001             748          18    5528.83
1002             748          21    4389.77
1003             755          20    4860.34
1004             753          25    8050.55

In [ ]:
rfm['R_Score'] = pd.qcut(rfm['Recencia'], 3, labels=[3,2,1])
rfm[['Recencia','R_Score']].head()

            Recencia R_Score
ID_Cliente
1000             757       2
1001             748       3
1002             748       3
1003             755       2
1004             753       3

In [ ]:
rfm['F_Score'] = pd.qcut(rfm['Frecuencia'], 3, labels=[1,2,3])
rfm[['Frecuencia','F_Score']].head()

            Frecuencia F_Score
ID_Cliente
1000                21       2
1001                18       1
1002                21       2
1003                20       2
1004                25       3

In [ ]:
rfm['M_Score'] = pd.qcut(rfm['Monetario'], 3, labels=[1,2,3])
rfm[['Monetario','M_Score']].head()

            Monetario M_Score
ID_Cliente
1000          5304.32       2
1001          5528.83       2
1002          4389.77       1
1003          4860.34       1
1004          8050.55       3

In [ ]:
print(rfm.head())

            Recencia  Frecuencia  Monetario R_Score F_Score M_Score
ID_Cliente
1000             757          21    5304.32       2       2       2
1001             748          18    5528.83       3       1       2
1002             748          21    4389.77       3       2       1
1003             755          20    4860.34       2       2       1
1004             753          25    8050.55       3       3       3

In [ ]:
segmentos = [ 'Campeones', 'Leales', 'En Riesgo', 'Perdidos', 'Nuevos' ]

In [ ]:
rfm['R_Score'] = pd.qcut(rfm['Recencia'], 3, labels=[3,2,1]).astype(int)
rfm['F_Score'] = pd.qcut(rfm['Frecuencia'], 3, labels=[1,2,3]).astype(int)
rfm['M_Score'] = pd.qcut(rfm['Monetario'], 3, labels=[1,2,3]).astype(int)

In [ ]:
condiciones = [ (rfm['R_Score'] == 3) & (rfm['F_Score'] == 3) & (rfm['M_Score'] == 3), # campeones
                 (rfm['F_Score'] == 3), # leales
                 (rfm['R_Score'] == 1) & ((rfm['F_Score'] == 3) | (rfm['M_Score'] == 3)), # en Riesgo
                 (rfm['R_Score'] == 1) & (rfm['F_Score'] == 1) & (rfm['M_Score'] == 1), # perdidos
                 (rfm['R_Score'] == 3) & (rfm['F_Score'] == 1) # nuevos
                 ]

In [ ]:
rfm['Segmento'] = np.select(condiciones, segmentos, default='Otros')

In [ ]:
print(rfm[['Recencia','R_Score','Frecuencia','F_Score','Monetario','M_Score','Segmento']].head())

            Recencia  R_Score  Frecuencia  F_Score  Monetario  M_Score  \
ID_Cliente
1000             757        2          21        2    5304.32        2
1001             748        3          18        1    5528.83        2
1002             748        3          21        2    4389.77        1
1003             755        2          20        2    4860.34        1
1004             753        3          25        3    8050.55        3

             Segmento
ID_Cliente
1000            Otros
1001           Nuevos
1002            Otros
1003            Otros
1004        Campeones

In [ ]:
rfm

,Recencia,Frecuencia,Monetario,R_Score,F_Score,M_Score,Segmento
ID_Cliente,,,,,,,
1000,757,21,5304.32,2,2,2,Otros
1001,748,18,5528.83,3,1,2,Nuevos
1002,748,21,4389.77,3,2,1,Otros
1003,755,20,4860.34,2,2,1,Otros
1004,753,25,8050.55,3,3,3,Campeones
1005,748,22,6076.92,3,3,3,Campeones
1006,777,15,4359.10,1,1,1,Perdidos
1007,747,20,6304.75,3,2,3,Otros
1008,756,21,4970.26,2,2,2,Otros
1009,776,21,4994.28,1,2,2,Otros
1010,749,21,5929.29,3,2,3,Otros
1011,789,15,4344.37,1,1,1,Perdidos
1012,796,18,5782.74,1,1,2,Otros
1013,761,21,5701.11,2,2,2,Otros
1014,770,19,4733.40,2,2,1,Otros
1015,782,10,2408.31,1,1,1,Perdidos
1016,747,26,7247.43,3,3,3,Campeones
1017,753,20,4938.43,3,2,2,Otros
1018,754,14,4416.59,3,1,1,Nuevos
1019,770,15,4592.74,2,1,1,Otros
1020,824,19,4916.79,1,2,2,Otros
1021,784,18,5153.03,1,1,2,Otros
1022,750,23,7648.22,3,3,3,Campeones
1023,749,20,6060.55,3,2,3,Otros
1024,770,25,5592.85,2,3,2,Leales
1025,780,31,9729.62,1,3,3,Leales
1026,773,14,4802.74,1,1,1,Perdidos
1027,751,16,3099.02,3,1,1,Nuevos
1028,762,23,5410.94,2,3,2,Leales
1029,760,23,7017.32,2,3,3,Leales
1030,748,15,5642.80,3,1,2,Nuevos
1031,766,17,5999.65,2,1,3,Otros
1032,797,22,7864.36,1,3,3,Leales
1033,753,29,7315.72,3,3,3,Campeones
1034,786,20,5713.11,1,2,2,Otros
1035,762,16,4393.43,2,1,1,Otros
1036,786,28,7680.12,1,3,3,Leales
1037,763,21,5357.35,2,2,2,Otros
1038,751,17,4803.92,3,1,1,Nuevos
1039,762,29,7123.52,2,3,3,Leales
1040,771,13,3479.34,1,1,1,Perdidos
1041,763,16,5471.71,2,1,2,Otros
1042,763,20,4874.05,2,2,2,Otros
1043,780,18,4717.36,1,1,1,Perdidos
1044,767,25,6184.05,2,3,3,Leales
1045,756,15,4125.24,2,1,1,Otros
1046,749,30,7642.16,3,3,3,Campeones
1047,789,13,2318.11,1,1,1,Perdidos
1048,752,26,6999.76,3,3,3,Campeones
1049,760,15,3865.15,2,1,1,Otros

In [ ]:
print(rfm['Segmento'].value_counts())

Segmento
Otros        23
Leales        8
Campeones     7
Perdidos      7
Nuevos        5
Name: count, dtype: int64